Minor Changes to output merge statements
transmute-industries/jsonld-to-cypher pull request #19
Opened 2023-03-22 17:45 UTC by bluisana

expanded the blanknode identification by passing the entire nodelabel to the blanknode method. 

changed the nodetonodelabel method to output multiple labels as an array rather than a colon separated string.

2023-03-23 13:37 UTC, nissimsan requested changes

2023-03-23 13:37 UTC, nissimsan commented on src/jsonGraphToCypher.js
> +    // testing to get to our prob nodes
This needs to go

2023-03-29 19:46 UTC, nissimsan requested changes

2023-03-29 19:46 UTC, nissimsan commented on vp2.json
> +                "type": ["GeoCoordinates"]
These empty elements are quite weird.

2023-03-29 19:47 UTC, nissimsan requested changes

2023-03-29 19:47 UTC, nissimsan commented on src/jsonGraphToCypher.js
> +    // check if the node or nodelabel have blank node identifiers in them
😍 Comments!!!

2023-03-29 19:48 UTC, nissimsan commented on src/jsonGraphToCypher.js
> +    // if either nodeid or the nodelable have blank node identifiers then this is a blank node
😍 Comments!!!

2023-03-30 13:15 UTC, bluisana commented on vp2.json
> +                "type": ["GeoCoordinates"]
irrelevant file has been removed.

2023-03-30 19:46 UTC, nissimsan approved these changes
This looks solid

2023-03-31 15:12 UTC, merged